# AFK Monitor Optional Config
# This file contains optional settings that can be used in afk_monitor.toml
#
# SETTINGS HERE ARE FOR INFO ONLY - THIS FILE IS NOT LOADED BY AFK MONITOR!
# 
# To modify a setting, copy and paste it under [Settings] in afk_monitor.toml

[Settings]
# RecentFiles specifies number of files to show with --fileselect (default: 10)
RecentFiles = 10
# TruncatePirate shortens names of pirates above this length in kill logs (default: 25)
TruncatePirate = 25
# TruncateFaction shortens names of factions above this length in kill logs (default: 30)
TruncateFaction = 30
# WarnNoKillsInitial is the time in minutes before warning of no kills at session start (default: 5)
WarnNoKillsInitial = 5
# WarnKillRateDelay is the time in minutes before warning of low kill rate at session start (default: 5)
WarnKillRateDelay = 5
# WarnCooldown is the time in minutes before repeating kill rate warnings, doubled thereafter (default: 30)
WarnCooldown = 30
# RecentAverageNum is the number of recent kills/scans to report on in ExtendedStats (default: 10)
RecentAverageNum = 10
